---
# tasks file for fuzzing-server

- name: Git checkout
  git:
    repo: 'https://github.com/sigp/beacon-fuzz.git'
    dest: "{{ FUZZING_HOME }}/beacon-fuzz"

- name: make and run fuzzer on screen
  become: yes
  shell: screen -d -c "cd {{ FUZZING_HOME }}/beacon-fuzz/eth2fuzz; make {{ fuzzing_target }}; sleep 1"

