---
# tasks file for fuzzing-server
- name: Create fuzzing folder location
  file:
    path: "{{ FUZZING_HOME }}"
    state: directory

- name: Git checkout
  git:
    repo: 'https://github.com/sigp/beacon-fuzz.git'
    dest: "{{ FUZZING_HOME }}/beacon-fuzz"

- name: make and run fuzzer on screen
  become: true
  shell: screen -d -m sh -c "cd {{ FUZZING_HOME }}/beacon-fuzz/eth2fuzz; make {{ fuzzing_target }}; sleep 30"