- hosts: "{{ playbook_hosts | default('servers') }}"
  vars_files:
    - variables/folder-location.yaml
  tasks:
    - name: ansible create directory example
      delegate_to: localhost
      file:
        path: ../fuzzing-artifacts/{{ inventory_hostname }}
        state: directory
    - name: Pull the eth2fuzz fuzzing artifacts to the local system using rsync
      when: tool == 'eth2fuzz'
      ansible.posix.synchronize:
        mode: pull
        src: "{{ ETH2FUZZ_ARTIFACT_LOCATION }}"
        dest: ../fuzzing-artifacts/eth2fuzz/{{ inventory_hostname }}
    - name: Pull the beaconfuzz_v2 fuzzing artifacts to the local system using rsync
      when: tool == 'beaconfuzz_v2'
      ansible.posix.synchronize:
        mode: pull
        src: "{{ BEACONFUZZ_V2_ARTIFACT_LOCATION }}"
        dest: ../fuzzing-artifacts/beaconfuzz_v2/{{ inventory_hostname }}