- hosts: all
  become: yes
  tasks:
    - name: stop all fuzzing runs - and make
      become: yes
      shell: screen -d -m bash -c "sleep 1; pkill make;"
    - name: stop all fuzzing runs - and screen
      become: yes
      shell: screen -ls | grep Detached | cut -d. -f1 | awk '{print $1}' | xargs kill
